apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-cert
  namespace: kb-system
spec:
  dnsNames:
  - kb-controller-manager-service.kb-system.svc
  secretName: webhook-server-cert
  issuerRef:
    name: webhook-issuer
