apiVersion: v1
kind: TestTrigger
metadata:
  name: test-trigger
spec:
  resourceEvents:
    # case 1 Event의 type 필드가 Warning인 경우
  - resource:
      apiVersion: v1
      kind: Event
      namespace: default
      name: ""
      labels:
        app: gateway
    conditions: # 조건이 여러 개 인 경우(OR로 처리 즉 각각 검사)
    - statusCondition:
      field: type
      operator: Equals
      status: Warning
    message:
      level: warning
      message: "message"
    notifications:
    - type: mattermost
      url: "mattermost-webhook-url"

    # case 2 ClusterInfo의 status.phase 필드가 NotReady로 변경된 경우
  - resource:
      apiVersion: v1
      kind: ClusterInfo
      namespace: default
      name: ""
      labels:
        app: gateway
    conditions:
    -statusCondition:
      field: status.phase
      operator: Equals
      status: NotReady
    message:
      level: error
      message: "message"
    notifications:
    - type: mattermost
      url: "mattermost-webhook-url"
    - type: gmail
      smtpServer: smtp-server
      smtpPort: 587
      username: userEmail
      password: userPassword
      fromAddress: fromuser@mantech.co.kr
      toAddress: touser@mantech.co.kr
      subject: 제목
      message: 메일 내용

    # case 3 acc-system namespace에서 member-agent라는 이름의 Deployment의 image 필드가 특정 버전 보다 낮은 경우
  - resource:
      apiVersion: apps/v1
      kind: Deployment
      namespace: acc-system
      name: member-agent
      labels:
        app: gateway
    conditions:
    - valueCondition:
      field: spec.template.spec.containers[0].image
      operator: LessThan
      value: "image-version"
    message:
      level: info
      message: "message"
    notifications:
    - type: mattermost
      url: "mattermost-webhook-url"
    # case 4 acc-global namespace에서 app: gateway 라벨을 가진 Pod의 status.phase 필드가 Running이 아닌 경우
  - resource:
      apiVersion: v1
      kind: Pod
      namespace: acc-global
      name: ""
      labels:
        app: gateway
    conditions:
    - statusCondition:
      field: status.phase
      operator: NotEquals
      value: Running
    message:
      level: error
      message: "message"
    notifications:
    - type: mattermost
      url: "mattermost-webhook-url"
status:
  resourceStatuses:
  - name: resource-name
    kind: pod
    Conditions:
    - field: status.phase
      operator: NotEquals
      status: NotEquals
    lastNotificationTime : 마지막 알림 전송 시간
    firstNotificationTime : 첫 알림 전송 시간
    notificationCount : 알림 횟수


