# permissions for end users to edit eventtriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kb
    app.kubernetes.io/managed-by: kustomize
  name: eventtrigger-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - eventtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - eventtriggers/status
  verbs:
  - get
