# permissions for end users to view testpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kb
    app.kubernetes.io/managed-by: kustomize
  name: testpod-viewer-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - testpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - testpods/status
  verbs:
  - get
